### ISSUE TITLE
Strange error causes page to hang after submitting Bureaucracy form with Struct data

### ISSUE THREAD

**Issue by armandostyl** [nomadjimbob/mikioplugin#29]
Page hangs upon submission of burraucracy form with Struct data and I get this error.
I have the include plugin, which corresponds to a tab in the template with an included page with different ACL (admin tab).
Any idea what's going on?

```
2024-01-06 09:42:46E_WARNING: Undefined array key "width"/home/staging/lib/plugins/mikioplugin/syntax/nav.php(37)
    #0 /home/staging/lib/plugins/mikioplugin/syntax/nav.php(37): dokuwiki\ErrorHandler::errorHandler()
    #1 /home/staging/lib/plugins/mikioplugin/syntax/core.php(406): syntax_plugin_mikioplugin_nav->render_lexer_enter()
    #2 /home/staging/inc/parser/renderer.php(119): syntax_plugin_mikioplugin_core->render()
    #3 /home/staging/inc/parserutils.php(700): Doku_Renderer->plugin()
    #4 /home/staging/inc/parserutils.php(158): p_render()
    #5 /home/staging/inc/parserutils.php(96): p_cached_output()
    #6 /home/staging/inc/template.php(1592): p_wiki_xhtml()
    #7 /home/staging/lib/tpl/mikio/mikio.php(491): tpl_include_page()
    #8 /home/staging/lib/tpl/mikio/mikio.php(987): dokuwiki\template\mikio\Template->includePage()
    #9 /home/staging/lib/tpl/mikio/main.php(73): dokuwiki\template\mikio\Template->includeSidebar()
    #10 /home/staging/inc/actions.php(27): include('/home/staging/...')
    #11 /home/staging/doku.php(126): act_dispatch()
    #12 {main}
2024-01-06 09:42:46E_WARNING: Undefined array key "height"/home/staging/lib/plugins/mikioplugin/syntax/nav.php(37)
    #0 /home/staging/lib/plugins/mikioplugin/syntax/nav.php(37): dokuwiki\ErrorHandler::errorHandler()
    #1 /home/staging/lib/plugins/mikioplugin/syntax/core.php(406): syntax_plugin_mikioplugin_nav->render_lexer_enter()
    #2 /home/staging/inc/parser/renderer.php(119): syntax_plugin_mikioplugin_core->render()
    #3 /home/staging/inc/parserutils.php(700): Doku_Renderer->plugin()
    #4 /home/staging/inc/parserutils.php(158): p_render()
    #5 /home/staging/inc/parserutils.php(96): p_cached_output()
    #6 /home/staging/inc/template.php(1592): p_wiki_xhtml()
    #7 /home/staging/lib/tpl/mikio/mikio.php(491): tpl_include_page()
    #8 /home/staging/lib/tpl/mikio/mikio.php(987): dokuwiki\template\mikio\Template->includePage()
    #9 /home/staging/lib/tpl/mikio/main.php(73): dokuwiki\template\mikio\Template->includeSidebar()
    #10 /home/staging/inc/actions.php(27): include('/home/greeceof/...')
    #11 /home/staging/doku.php(126): act_dispatch()
    #12 {main}
```

**Comment by nomadjimbob** [comment]
Fixed in the latest update (2024-01-06). It appeared that when you don't use a width and height in the nav element, the default values were not set correctly and caused this error.
